<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\User;
use App\Models\Role;
use App\Models\Entity;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class UserSeeder extends Seeder
{
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        User::query()->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        // Ambil ID dari role yang sudah ada
        $roles = Role::pluck('id', 'name');
        $defaultPassword = Hash::make('TrenggalekMeroket#!');

        // --- PENGGUNA INTERNAL INSPEKTORAT ---
        $internalUsers = [
            ['name' => 'DIDIK AGIT W, SE.MAP', 'email' => 'diekagita@gmail.com', 'role' => 'Auditor', 'nip' => '196612061992031009', 'jabatan' => 'Auditor Madya'],
            ['name' => 'DIDIK SUPRIYANTO, S.Sos.M.Si', 'email' => 'didieks@yahoo.co.id', 'role' => 'Auditor', 'nip' => '196612221992021001', 'jabatan' => 'P2UPD Madya'],
            ['name' => 'Ir. BENNO HERA T.', 'email' => 'bennohera100@gmail.com', 'role' => 'Auditor', 'nip' => '196706162006041010', 'jabatan' => 'Auditor Madya'],
            ['name' => 'Ir.AGUNG SRIYONO', 'email' => 'srsagoeng@gmail.com', 'role' => 'Auditor', 'nip' => '196706261994031008', 'jabatan' => 'P2UPD Madya'],
            ['name' => 'APIP MUTOHARI, SH.M.Si', 'email' => 'apipmutohari19@gmail.com', 'role' => 'Pejabat Struktural', 'nip' => '196707191993021002', 'jabatan' => 'Inspektur Pembantu I'],
            ['name' => 'DJOKO PURNOMO,SE', 'email' => 'djokop975@gmail.com', 'role' => 'Auditor', 'nip' => '196708221991031013', 'jabatan' => 'P2UPD Madya'],
            ['name' => 'KATIRAN', 'email' => '68katiran@gmail.com', 'role' => 'Pegawai', 'nip' => '196810202007011015', 'jabatan' => 'Pengadministrasi Perkantoran'],
            ['name' => 'SUYATNO,SH', 'email' => 'ytnos69@gmail.com', 'role' => 'Pejabat Struktural', 'nip' => '196906221992021001', 'jabatan' => 'Inspektur Pembantu III'],
            ['name' => 'SULIS SETYAWATI', 'email' => 'inspektoratsulis@gmail.com', 'role' => 'Pegawai', 'nip' => '197004062005012001', 'jabatan' => 'Pengadministrasi Perkantoran'],
            ['name' => 'UTARI PRASETYANI,SE', 'email' => 'setyatari.teguh@gmail.com', 'role' => 'Auditor', 'nip' => '197101042010012003', 'jabatan' => 'Auditor Muda'],
            ['name' => 'EKO DARMINTO,SE.MSi', 'email' => 'ekominto1972@gmail.com', 'role' => 'Auditor', 'nip' => '197203171998031007', 'jabatan' => 'P2UPD Madya'],
            ['name' => 'Ir. WIJIONO, S.T., M.MKes.', 'email' => 'onowiji2@gmail.com', 'role' => 'Pejabat Struktural', 'nip' => '197308051997031007', 'jabatan' => 'Sekretaris'],
            ['name' => 'SIGIT PRASETYO,S.IP.,MAP', 'email' => 'sigit.prasetyo1973@gmail.com', 'role' => 'Pejabat Struktural', 'nip' => '197310211993101001', 'jabatan' => 'Inspektur Pembantu IV'],
            ['name' => 'YENI KRISTUTI', 'email' => 'yenikristuti@gmail.com', 'role' => 'Pegawai', 'nip' => '197601012005012020', 'jabatan' => 'Pengadministrasi Perkantoran'],
            ['name' => 'TOTOK SUBIANTO, SE', 'email' => 'subiantototok69@gmail.com', 'role' => 'Auditor', 'nip' => '197701252010011008', 'jabatan' => 'Auditor Madya'],
            ['name' => 'ENI SUMAWATI, SE', 'email' => 'enisumawati2@gmail.com', 'role' => 'Auditor', 'nip' => '197702222010012008', 'jabatan' => 'Auditor Muda'],
            ['name' => 'RIKE ARSHINTA MAYASARI, ST', 'email' => 'rikearshinta@gmail.com', 'role' => 'Auditor', 'nip' => '197705022009032006', 'jabatan' => 'Auditor Muda'],
            ['name' => 'NUGRAHENI RAHAYU SETYANINGSIH', 'email' => 'nugrahenirahayusetyaningsih@gmail.com', 'role' => 'Pejabat Struktural', 'nip' => '197211141994022001', 'jabatan' => 'Kepala Sub Bagian Umum dan Kepegawaian'],
            ['name' => 'NIKEN SRI PALUPI,SE', 'email' => 'nikenjarvis@gmail.com', 'role' => 'Auditor', 'nip' => '197708092010012007', 'jabatan' => 'Auditor Muda'],
            ['name' => 'BASORI, ST', 'email' => 'b4sori1209@gmail.com', 'role' => 'Auditor', 'nip' => '197709012011011003', 'jabatan' => 'Auditor Madya'],
            ['name' => 'KUSNUL KOTIMAH', 'email' => 'khusnulktmh@gmail.com', 'role' => 'Pegawai', 'nip' => '197805112006042026', 'jabatan' => 'Pengadministrasi Perkantoran'],
            ['name' => 'HARYADI', 'email' => 'hariadi.ispk@gmail.com', 'role' => 'Pegawai', 'nip' => '197807132009011001', 'jabatan' => 'Pengadministrasi Perkantoran'],
            ['name' => 'SULIKAH', 'email' => 'sulikahstp@gmail.com', 'role' => 'Pegawai', 'nip' => '198505212014022001', 'jabatan' => 'Pengolah Data dan Informasi'],
            ['name' => 'SIGIH SETIONO, A. Md', 'email' => 'sigih.ute@gmail.com', 'role' => 'Auditor', 'nip' => '197908012009031003', 'jabatan' => 'Auditor Penyelia'],
            ['name' => 'DWI SUCI RAHAYU, SE.', 'email' => 'dwisucirahayuse@gmail.com', 'role' => 'Auditor', 'nip' => '197912072009032004', 'jabatan' => 'Auditor Madya'],
            ['name' => 'NANANG MARDIANTORO', 'email' => 'nanangmardiantoro@gmail.com', 'role' => 'Pegawai', 'nip' => '198008282005011011', 'jabatan' => 'Pengadministrasi Perkantoran'],
            ['name' => 'ROEKAN, A.Md', 'email' => 'roekan@gmail.com', 'role' => 'Pegawai', 'nip' => '198102052006041010', 'jabatan' => 'Pengolah Data dan Informasi'],
            ['name' => 'UMROTUL MAHFUDHOH, A.Md', 'email' => 'umrotulmahfudhoh9@gmail.com', 'role' => 'Auditor', 'nip' => '198305302009032004', 'jabatan' => 'Auditor Penyelia'],
            ['name' => 'WINDU SETIYADI, ST', 'email' => 'winduws9@gmail.com', 'role' => 'Auditor', 'nip' => '198401192010011016', 'jabatan' => 'Auditor Muda'],
            ['name' => 'HAPPY RAHMAWATI,SE', 'email' => 'happyrahmawati01@gmail.com', 'role' => 'Auditor', 'nip' => '198501042010012010', 'jabatan' => 'Auditor Muda'],
            ['name' => 'FENY RATNAWATI,SE', 'email' => 'fenyratnawati@gmail.com', 'role' => 'Auditor', 'nip' => '198602152006042005', 'jabatan' => 'Auditor Muda'],
            ['name' => 'CAHYA FITRIA ARDIANI, A. Md', 'email' => 'ardiani86.cahya@gmail.com', 'role' => 'Pegawai', 'nip' => '198606242011012021', 'jabatan' => 'Penelaah Teknis Kebijakan'],
            ['name' => 'NANDITO MONLIEV PASSA,S.Kom', 'email' => 'nanditomonlievpassa@gmail.com', 'role' => 'Super Admin', 'nip' => '199011272015031003', 'jabatan' => 'Penelaah Teknis Kebijakan'],
            ['name' => 'CHOIRUNNISA,S.A.', 'email' => 'chnisa02@gmail.com', 'role' => 'Auditor', 'nip' => '199307022022032002', 'jabatan' => 'Auditor Pertama'],
            ['name' => 'ANANDA SEPTA WILLYANDA,S.E.', 'email' => 'anandaseptawillyanda@gmail.com', 'role' => 'Auditor', 'nip' => '199709262022031007', 'jabatan' => 'Auditor Pertama'],
            ['name' => 'PUSPANAGARI PUTRI RIDANTI,S.Ak', 'email' => 'pusparidanti98@gmail.com', 'role' => 'Auditor', 'nip' => '199812012022032002', 'jabatan' => 'Auditor Pertama'],
            ['name' => 'ABYADH NURUTTIMAMI F R,A.Md.Ak', 'email' => 'abyadhnurfahridho99@gmail.com', 'role' => 'Auditor', 'nip' => '199812172022031001', 'jabatan' => 'Auditor Terampil'],
            ['name' => 'MUHAMAD IQBAL MAULIDI,A.Md.Ak', 'email' => 'iqbalmaulidi0107@gmail.com', 'role' => 'Auditor', 'nip' => '199907012022031001', 'jabatan' => 'Auditor Terampil'],
            ['name' => 'DESTY AYU SAPUTRI,A.Md.Ak', 'email' => 'desti.sapu999@gmail.com', 'role' => 'Auditor', 'nip' => '199912042022032001', 'jabatan' => 'Auditor Terampil'],
            ['name' => 'FEREN FEBRIYANTI,S.Ak', 'email' => 'ferenfebriyanti2@gmail.com', 'role' => 'Auditor', 'nip' => '199912212022032003', 'jabatan' => 'Auditor Pertama'],
            ['name' => 'MUHAMMAD IDHAM FIRDAUS,A.Md.Ak', 'email' => 'idhamfirdaus11@gmail.com', 'role' => 'Auditor', 'nip' => '200001142022031001', 'jabatan' => 'Auditor Terampil'],
            ['name' => 'NADIAH FIRDAUSSINTA D., A.Md.Ak.', 'email' => 'nadiahsinta29@gmail.com', 'role' => 'Auditor', 'nip' => '200002292022032002', 'jabatan' => 'Auditor Terampil'],
            ['name' => 'ANINDYA FAUZIYAH BASUKI,A.Md.Ak', 'email' => 'akyungie@gmail.com', 'role' => 'Auditor', 'nip' => '200003092022032001', 'jabatan' => 'Auditor Terampil'],
            ['name' => 'ANDIKA PUTRA HARDYANSYAH,A,Md.Ak', 'email' => 'hardyansyahaph@gmail.com', 'role' => 'Auditor', 'nip' => '200006032022031002', 'jabatan' => 'Auditor Terampil'],
            ['name' => 'FERYAL NADA AZIZAH,A.Md.Ak', 'email' => 'feryalnadaazizah@gmail.com', 'role' => 'Auditor', 'nip' => '200008262022032001', 'jabatan' => 'Auditor Terampil'],
            ['name' => 'CHRIS TRYANTO MARTA P P,A,Md.Ak', 'email' => 'chris.tmpp@gmail.com', 'role' => 'Auditor', 'nip' => '200103072022031001', 'jabatan' => 'Auditor Terampil'],
            ['name' => 'Yopi Adi Prayoga', 'email' => 'yopiprayoga95@gmail.com', 'role' => 'Auditor', 'nip' => '199508112025061002', 'jabatan' => 'P2UPD Pertama'],
            ['name' => 'Erni Agustina', 'email' => 'erniagustina.bogi@gmail.com', 'role' => 'Auditor', 'nip' => '199008172025062002', 'jabatan' => 'Auditor Pertama'],
            ['name' => 'Fellis Enricha Putri', 'email' => 'fellisputri12@gmail.com', 'role' => 'Auditor', 'nip' => '199907122025062006', 'jabatan' => 'P2UPD Pertama'],
            ['name' => 'Roro Putri Setianingayu', 'email' => 'roroputri0107@gmail.com', 'role' => 'Auditor', 'nip' => '200107012025062011', 'jabatan' => 'P2UPD Pertama'],
            ['name' => 'Muhammad Aditya Kriswahyudi', 'email' => 'adityamuhammad99k@gmail.com', 'role' => 'Auditor', 'nip' => '199904212025061006', 'jabatan' => 'P2UPD Pertama'],
            ['name' => 'Irmala Prasistya Cahyaning Putri', 'email' => 'irmalaprasistya00@gmail.com', 'role' => 'Auditor', 'nip' => '200002052025062009', 'jabatan' => 'Auditor Pertama'],
            ['name' => 'Mela Endriani', 'email' => 'melaedr@gmail.com', 'role' => 'Auditor', 'nip' => '200005122025062008', 'jabatan' => 'P2UPD Pertama'],
            ['name' => 'Moh. Muhadhir Syafaat', 'email' => 'muhadhirs@gmail.com', 'role' => 'Auditor', 'nip' => '199606232025061003', 'jabatan' => 'P2UPD Pertama'],
            ['name' => 'Indah Nabila Hasna', 'email' => 'indahnabila06@gmail.com', 'role' => 'Auditor', 'nip' => '200207062025062012', 'jabatan' => 'Auditor Pertama'],
            ['name' => 'Zakiatul Mufarrihah', 'email' => 'yaa.zakiya@gmail.com', 'role' => 'Auditor', 'nip' => '199812242025062009', 'jabatan' => 'Auditor Pertama'],
            ['name' => 'Devi Selvia', 'email' => 'deviselviaaaa@gmail.com', 'role' => 'Auditor', 'nip' => '199912012025062009', 'jabatan' => 'P2UPD Pertama'],
            ['name' => 'Kukuh Ari Firmansyah', 'email' => 'kukuh.arifirmansyah16@gmail.com', 'role' => 'Auditor', 'nip' => '200205272025061001', 'jabatan' => 'Auditor Pertama'],
            ['name' => 'Nuventin Asna Putri', 'email' => 'nuventinputri@gmail.com', 'role' => 'Auditor', 'nip' => '200011142025062004', 'jabatan' => 'Auditor Pertama'],
            ['name' => 'Aji Surya Saksama', 'email' => 'saksamaaji@gmail.com', 'role' => 'Auditor', 'nip' => '199606152025061005', 'jabatan' => 'P2UPD Pertama'],
            ['name' => 'Tommy Kurniawan', 'email' => 'tmmkurniawan@gmail.com', 'role' => 'Auditor', 'nip' => '199305102025061003', 'jabatan' => 'P2UPD Pertama'],
            ['name' => 'Diah Ajeng Meliasari', 'email' => 'ddiahaajg@gmail.com', 'role' => 'Auditor', 'nip' => '200011252025062009', 'jabatan' => 'P2UPD Pertama'],
            ['name' => 'Putri Patrisia Fernanda', 'email' => 'putripatrisiaf31@gmail.com', 'role' => 'Auditor', 'nip' => '200203312025062009', 'jabatan' => 'Auditor Pertama'],
            ['name' => 'Kartika Kusuma Dewi', 'email' => 'kartika.kusuma.dewi7@gmail.com', 'role' => 'Auditor', 'nip' => '199609082025062006', 'jabatan' => 'P2UPD Pertama'],
            ['name' => 'Fryza Rachmania Mashuri', 'email' => 'fryza.rachmania@gmail.com', 'role' => 'Pegawai', 'nip' => '199910122025062012', 'jabatan' => 'Pranata Komputer Terampil'],
            ['name' => 'ADHI TRIYANTO, S.Tr.I.P.', 'email' => 'adhitriyanto@gmail.com', 'role' => 'Auditor', 'nip' => '200212162024091001', 'jabatan' => 'P2UPD Pertama'],
        ];

        foreach ($internalUsers as $userData) {
            User::create([
                'name' => $userData['name'],
                'email' => $userData['email'],
                'password' => $defaultPassword,
                'role_id' => $roles[$userData['role']] ?? null,
                'nip' => $userData['nip'],
                'jabatan' => $userData['jabatan'],
            ]);
        }
        
        // --- PENGGUNA EKSTERNAL (GENERATED) ---
        $klienRoleId = $roles['Klien Eksternal'] ?? null;
        if($klienRoleId) {
            $externalClientData = [
                ['name' => 'Badan Kepegawaian Daerah', 'email' => 'badan.kepegawaian@trenggalekkab.go.id'],
                ['name' => 'Badan Kesatuan Bangsa dan Politik', 'email' => 'badan.kesatuanbangsa@trenggalekkab.go.id'],
                ['name' => 'Badan Keuangan Daerah', 'email' => 'badan.keuangan@trenggalekkab.go.id'],
                ['name' => 'Badan Penanggulangan Bencana Daerah', 'email' => 'badan.penanggulanganbencana@trenggalekkab.go.id'],
                ['name' => 'Badan Perencanaan Pembangunan, Penelitian dan Pengembangan Daerah', 'email' => 'badan.perencanaan@trenggalekkab.go.id'],
                ['name' => 'Bagian Administrasi Pembangunan', 'email' => 'bagian.administrasi@trenggalekkab.go.id'],
                ['name' => 'Bagian Hukum', 'email' => 'bagian.hukum@trenggalekkab.go.id'],
                ['name' => 'Bagian Kesejahteraan Rakyat', 'email' => 'bagian.kesejahteraan@trenggalekkab.go.id'],
                ['name' => 'Bagian Organisasi', 'email' => 'bagian.organisasi@trenggalekkab.go.id'],
                ['name' => 'Bagian Pemerintahan', 'email' => 'bagian.pemerintahan@trenggalekkab.go.id'],
                ['name' => 'Bagian Pengadaan Barang dan Jasa', 'email' => 'bagian.pengadaan@trenggalekkab.go.id'],
                ['name' => 'Bagian Perekonomian dan Sumber Daya Alam', 'email' => 'bagian.perekonomian@trenggalekkab.go.id'],
                ['name' => 'Dinas Kearsipan dan Perpustakaan', 'email' => 'dinas.kearsipan@trenggalekkab.go.id'],
                ['name' => 'Dinas Kependudukan Dan Pencatatan Sipil', 'email' => 'dinas.kependudukan@trenggalekkab.go.id'],
                ['name' => 'Dinas Kesehatan, Pengendalian Penduduk dan Keluarga Berencana', 'email' => 'dinas.kesehatan@trenggalekkab.go.id'],
                ['name' => 'Dinas Komunikasi dan Informatika', 'email' => 'dinas.komunikasi@trenggalekkab.go.id'],
                ['name' => 'Dinas Koperasi Dan Usaha Mikro dan Perdagangan', 'email' => 'dinas.koperasi@trenggalekkab.go.id'],
                ['name' => 'Dinas Pariwisata dan Kebudayaan', 'email' => 'dinas.pariwisata@trenggalekkab.go.id'],
                ['name' => 'Dinas Pekerjaan Umum dan Penataan Ruang', 'email' => 'dinas.pekerjaan@trenggalekkab.go.id'],
                ['name' => 'Dinas Pemberdayaan Masyarakat dan Desa', 'email' => 'dinas.pemberdayaan@trenggalekkab.go.id'],
                ['name' => 'Dinas Penanaman Modal dan Pelayanan Terpadu Satu Pintu', 'email' => 'dinas.penanamanmodal@trenggalekkab.go.id'],
                ['name' => 'Dinas Pendidikan, Pemuda dan Olahraga', 'email' => 'dinas.pendidikan@trenggalekkab.go.id'],
                ['name' => 'Dinas Perhubungan', 'email' => 'dinas.perhubungan@trenggalekkab.go.id'],
                ['name' => 'Dinas Perikanan', 'email' => 'dinas.perikanan@trenggalekkab.go.id'],
                ['name' => 'Dinas Perindustrian dan Tenaga Kerja', 'email' => 'dinas.perindustrian@trenggalekkab.go.id'],
                ['name' => 'Dinas Pertanian dan Pangan', 'email' => 'dinas.pertanian@trenggalekkab.go.id'],
                ['name' => 'Dinas Perumahan, Kawasan Permukiman dan Lingkungan Hidup', 'email' => 'dinas.perumahan@trenggalekkab.go.id'],
                ['name' => 'Dinas Peternakan', 'email' => 'dinas.peternakan@trenggalekkab.go.id'],
                ['name' => 'Dinas Sosial, Pemberdayaan Perempuan dan Perlindungan Anak', 'email' => 'dinas.sosial@trenggalekkab.go.id'],
                ['name' => 'Inspektorat', 'email' => 'inspektorat@trenggalekkab.go.id'],
                ['name' => 'Satuan Polisi Pamong Praja dan Kebakaran', 'email' => 'satpolpp.kebakaran@trenggalekkab.go.id'],
                ['name' => 'Sekretariat Daerah', 'email' => 'sekretariat.daerah@trenggalekkab.go.id'],
                ['name' => 'Sekretariat DPRD', 'email' => 'sekretariat.dprd@trenggalekkab.go.id'],
                ['name' => 'Kecamatan Bendungan', 'email' => 'kec.bendungan@trenggalekkab.go.id'],
                ['name' => 'Kecamatan Dongko', 'email' => 'kec.dongko@trenggalekkab.go.id'],
                ['name' => 'Kecamatan Durenan', 'email' => 'kec.durenan@trenggalekkab.go.id'],
                ['name' => 'Kecamatan Gandusari', 'email' => 'kec.gandusari@trenggalekkab.go.id'],
                ['name' => 'Kecamatan Kampak', 'email' => 'kec.kampak@trenggalekkab.go.id'],
                ['name' => 'Kecamatan Karangan', 'email' => 'kec.karangan@trenggalekkab.go.id'],
                ['name' => 'Kecamatan Munjungan', 'email' => 'kec.munjungan@trenggalekkab.go.id'],
                ['name' => 'Kecamatan Panggul', 'email' => 'kec.panggul@trenggalekkab.go.id'],
                ['name' => 'Kecamatan Pogalan', 'email' => 'kec.pogalan@trenggalekkab.go.id'],
                ['name' => 'Kecamatan Pule', 'email' => 'kec.pule@trenggalekkab.go.id'],
                ['name' => 'Kecamatan Suruh', 'email' => 'kec.suruh@trenggalekkab.go.id'],
                ['name' => 'Kecamatan Trenggalek', 'email' => 'kec.trenggalek@trenggalekkab.go.id'],
                ['name' => 'Kecamatan Tugu', 'email' => 'kec.tugu@trenggalekkab.go.id'],
                ['name' => 'Kecamatan Watulimo', 'email' => 'kec.watulimo@trenggalekkab.go.id'],
                ['name' => 'RSUD PANGGUL', 'email' => 'rsud.panggul@trenggalekkab.go.id'],
                ['name' => 'RSUD Dr. SOEDOMO', 'email' => 'rsud.soedomo@trenggalekkab.go.id'],
                ['name' => 'Puskesmas Panggul', 'email' => 'puskesmas.panggul@trenggalekkab.go.id'],
                ['name' => 'Puskesmas Bodag', 'email' => 'puskesmas.bodag@trenggalekkab.go.id'],
                ['name' => 'Puskesmas Munjungan', 'email' => 'puskesmas.munjungan@trenggalekkab.go.id'],
                ['name' => 'Puskesmas Watulimo', 'email' => 'puskesmas.watulimo@trenggalekkab.go.id'],
                ['name' => 'Puskesmas Slawe', 'email' => 'puskesmas.slawe@trenggalekkab.go.id'],
                ['name' => 'Puskesmas Kampak', 'email' => 'puskesmas.kampak@trenggalekkab.go.id'],
                ['name' => 'Puskesmas Dongko', 'email' => 'puskesmas.dongko@trenggalekkab.go.id'],
                ['name' => 'Puskesmas Pandean', 'email' => 'puskesmas.pandean@trenggalekkab.go.id'],
                ['name' => 'Puskesmas Pule', 'email' => 'puskesmas.pule@trenggalekkab.go.id'],
                ['name' => 'Puskesmas Karangan', 'email' => 'puskesmas.karangan@trenggalekkab.go.id'],
                ['name' => 'Puskesmas Suruh', 'email' => 'puskesmas.suruh@trenggalekkab.go.id'],
                ['name' => 'Puskesmas Gandusari', 'email' => 'puskesmas.gandusari@trenggalekkab.go.id'],
                ['name' => 'Puskesmas Karanganyar', 'email' => 'puskesmas.karanganyar@trenggalekkab.go.id'],
                ['name' => 'Puskesmas Durenan', 'email' => 'puskesmas.durenan@trenggalekkab.go.id'],
                ['name' => 'Puskesmas Baruharjo', 'email' => 'puskesmas.baruharjo@trenggalekkab.go.id'],
                ['name' => 'Puskesmas Pogalan', 'email' => 'puskesmas.pogalan@trenggalekkab.go.id'],
                ['name' => 'Puskesmas Ngulankulon', 'email' => 'puskesmas.ngulankulon@trenggalekkab.go.id'],
                ['name' => 'Puskesmas Trenggalek', 'email' => 'puskesmas.trenggalek@trenggalekkab.go.id'],
                ['name' => 'Puskesmas Rejowinangun', 'email' => 'puskesmas.rejowinangun@trenggalekkab.go.id'],
                ['name' => 'Puskesmas Tugu', 'email' => 'puskesmas.tugu@trenggalekkab.go.id'],
                ['name' => 'Puskesmas Pucanganak', 'email' => 'puskesmas.pucanganak@trenggalekkab.go.id'],
                ['name' => 'Puskesmas Bendungan', 'email' => 'puskesmas.bendungan@trenggalekkab.go.id'],
                ['name' => 'Desa Botoputih', 'email' => 'botoputih.bendungan@trenggalekkab.go.id'],
                ['name' => 'Desa Depok', 'email' => 'depok.bendungan@trenggalekkab.go.id'],
                ['name' => 'Desa Dompyong', 'email' => 'dompyong.bendungan@trenggalekkab.go.id'],
                ['name' => 'Desa Masaran', 'email' => 'masaran.bendungan@trenggalekkab.go.id'],
                ['name' => 'Desa Sengon', 'email' => 'sengon.bendungan@trenggalekkab.go.id'],
                ['name' => 'Desa Srabah', 'email' => 'srabah.bendungan@trenggalekkab.go.id'],
                ['name' => 'Desa Sumurup', 'email' => 'sumurup.bendungan@trenggalekkab.go.id'],
                ['name' => 'Desa Surenlor', 'email' => 'surenlor.bendungan@trenggalekkab.go.id'],
                ['name' => 'Desa Cakul', 'email' => 'cakul.dongko@trenggalekkab.go.id'],
                ['name' => 'Desa Dongko', 'email' => 'dongko.dongko@trenggalekkab.go.id'],
                ['name' => 'Desa Ngerdani', 'email' => 'ngerdani.dongko@trenggalekkab.go.id'],
                ['name' => 'Desa Pandean', 'email' => 'pandean.dongko@trenggalekkab.go.id'],
                ['name' => 'Desa Petung', 'email' => 'petung.dongko@trenggalekkab.go.id'],
                ['name' => 'Desa Pringapus', 'email' => 'pringapus.dongko@trenggalekkab.go.id'],
                ['name' => 'Desa Salamwates', 'email' => 'salamwates.dongko@trenggalekkab.go.id'],
                ['name' => 'Desa Siki', 'email' => 'siki.dongko@trenggalekkab.go.id'],
                ['name' => 'Desa Sumberbening', 'email' => 'sumberbening.dongko@trenggalekkab.go.id'],
                ['name' => 'Desa Watuagung', 'email' => 'watuagung.dongko@trenggalekkab.go.id'],
                ['name' => 'Desa Baruharjo', 'email' => 'baruharjo.durenan@trenggalekkab.go.id'],
                ['name' => 'Desa Durenan', 'email' => 'durenan.durenan@trenggalekkab.go.id'],
                ['name' => 'Desa Gador', 'email' => 'gador.durenan@trenggalekkab.go.id'],
                ['name' => 'Desa Kamulan', 'email' => 'kamulan.durenan@trenggalekkab.go.id'],
                ['name' => 'Desa Karanganom', 'email' => 'karanganom.durenan@trenggalekkab.go.id'],
                ['name' => 'Desa Kendalrejo', 'email' => 'kendalrejo.durenan@trenggalekkab.go.id'],
                ['name' => 'Desa Malasan', 'email' => 'malasan.durenan@trenggalekkab.go.id'],
                ['name' => 'Desa Ngadisuko', 'email' => 'ngadisuko.durenan@trenggalekkab.go.id'],
                ['name' => 'Desa Pakis', 'email' => 'pakis.durenan@trenggalekkab.go.id'],
                ['name' => 'Desa Pandean', 'email' => 'pandean.durenan@trenggalekkab.go.id'],
                ['name' => 'Desa Panggungsari', 'email' => 'panggungsari.durenan@trenggalekkab.go.id'],
                ['name' => 'Desa Semarum', 'email' => 'semarum.durenan@trenggalekkab.go.id'],
                ['name' => 'Desa Sumberejo', 'email' => 'sumberejo.durenan@trenggalekkab.go.id'],
                ['name' => 'Desa Sumbergayam', 'email' => 'sumbergayam.durenan@trenggalekkab.go.id'],
                ['name' => 'Desa Gandusari', 'email' => 'gandusari.gandusari@trenggalekkab.go.id'],
                ['name' => 'Desa Jajar', 'email' => 'jajar.gandusari@trenggalekkab.go.id'],
                ['name' => 'Desa Karanganyar', 'email' => 'karanganyar.gandusari@trenggalekkab.go.id'],
                ['name' => 'Desa Krandegan', 'email' => 'krandegan.gandusari@trenggalekkab.go.id'],
                ['name' => 'Desa Melis', 'email' => 'melis.gandusari@trenggalekkab.go.id'],
                ['name' => 'Desa Ngrayung', 'email' => 'ngrayung.gandusari@trenggalekkab.go.id'],
                ['name' => 'Desa Sukorame', 'email' => 'sukorame.gandusari@trenggalekkab.go.id'],
                ['name' => 'Desa Sukorejo', 'email' => 'sukorejo.gandusari@trenggalekkab.go.id'],
                ['name' => 'Desa Widoro', 'email' => 'widoro.gandusari@trenggalekkab.go.id'],
                ['name' => 'Desa Wonoanti', 'email' => 'wonoanti.gandusari@trenggalekkab.go.id'],
                ['name' => 'Desa Wonorejo', 'email' => 'wonorejo.gandusari@trenggalekkab.go.id'],
                ['name' => 'Desa Bendoagung', 'email' => 'bendoagung.kampak@trenggalekkab.go.id'],
                ['name' => 'Desa Bogoran', 'email' => 'bogoran.kampak@trenggalekkab.go.id'],
                ['name' => 'Desa Karangrejo', 'email' => 'karangrejo.kampak@trenggalekkab.go.id'],
                ['name' => 'Desa Ngadimulyo', 'email' => 'ngadimulyo.kampak@trenggalekkab.go.id'],
                ['name' => 'Desa Senden', 'email' => 'senden.kampak@trenggalekkab.go.id'],
                ['name' => 'Desa Sugihan', 'email' => 'sugihan.kampak@trenggalekkab.go.id'],
                ['name' => 'Desa Timahan', 'email' => 'timahan.kampak@trenggalekkab.go.id'],
                ['name' => 'Desa Buluagung', 'email' => 'buluagung.karangan@trenggalekkab.go.id'],
                ['name' => 'Desa Jati', 'email' => 'jati.karangan@trenggalekkab.go.id'],
                ['name' => 'Desa Jatiprahu', 'email' => 'jatiprahu.karangan@trenggalekkab.go.id'],
                ['name' => 'Desa Karangan', 'email' => 'karangan.karangan@trenggalekkab.go.id'],
                ['name' => 'Desa Kayen', 'email' => 'kayen.karangan@trenggalekkab.go.id'],
                ['name' => 'Desa Kedungsigit', 'email' => 'kedungsigit.karangan@trenggalekkab.go.id'],
                ['name' => 'Desa Kerjo', 'email' => 'kerjo.karangan@trenggalekkab.go.id'],
                ['name' => 'Desa Ngentrong', 'email' => 'ngentrong.karangan@trenggalekkab.go.id'],
                ['name' => 'Desa Salamrejo', 'email' => 'salamrejo.karangan@trenggalekkab.go.id'],
                ['name' => 'Desa Sukowetan', 'email' => 'sukowetan.karangan@trenggalekkab.go.id'],
                ['name' => 'Desa Sumber', 'email' => 'sumber.karangan@trenggalekkab.go.id'],
                ['name' => 'Desa Sumberingin', 'email' => 'sumberingin.karangan@trenggalekkab.go.id'],
                ['name' => 'Desa Bangun', 'email' => 'bangun.munjungan@trenggalekkab.go.id'],
                ['name' => 'Desa Bendoroto', 'email' => 'bendoroto.munjungan@trenggalekkab.go.id'],
                ['name' => 'Desa Besuki', 'email' => 'besuki.munjungan@trenggalekkab.go.id'],
                ['name' => 'Desa Craken', 'email' => 'craken.munjungan@trenggalekkab.go.id'],
                ['name' => 'Desa Karangturi', 'email' => 'karangturi.munjungan@trenggalekkab.go.id'],
                ['name' => 'Desa Masaran', 'email' => 'masaran.munjungan@trenggalekkab.go.id'],
                ['name' => 'Desa Munjungan', 'email' => 'munjungan.munjungan@trenggalekkab.go.id'],
                ['name' => 'Desa Ngulungkulon', 'email' => 'ngulungkulon.munjungan@trenggalekkab.go.id'],
                ['name' => 'Desa Ngulungwetan', 'email' => 'ngulungwetan.munjungan@trenggalekkab.go.id'],
                ['name' => 'Desa Sobo', 'email' => 'sobo.munjungan@trenggalekkab.go.id'],
                ['name' => 'Desa Tawing', 'email' => 'tawing.munjungan@trenggalekkab.go.id'],
                ['name' => 'Desa Banjar', 'email' => 'banjar.panggul@trenggalekkab.go.id'],
                ['name' => 'Desa Barang', 'email' => 'barang.panggul@trenggalekkab.go.id'],
                ['name' => 'Desa Besuki', 'email' => 'besuki.panggul@trenggalekkab.go.id'],
                ['name' => 'Desa Bodag', 'email' => 'bodag.panggul@trenggalekkab.go.id'],
                ['name' => 'Desa Depok', 'email' => 'depok.panggul@trenggalekkab.go.id'],
                ['name' => 'Desa Gayam', 'email' => 'gayam.panggul@trenggalekkab.go.id'],
                ['name' => 'Desa Karangtengah', 'email' => 'karangtengah.panggul@trenggalekkab.go.id'],
                ['name' => 'Desa Kertosono', 'email' => 'kertosono.panggul@trenggalekkab.go.id'],
                ['name' => 'Desa Manggis', 'email' => 'manggis.panggul@trenggalekkab.go.id'],
                ['name' => 'Desa Nglebeng', 'email' => 'nglebeng.panggul@trenggalekkab.go.id'],
                ['name' => 'Desa Ngrambingan', 'email' => 'ngrambingan.panggul@trenggalekkab.go.id'],
                ['name' => 'Desa Ngrencak', 'email' => 'ngrencak.panggul@trenggalekkab.go.id'],
                ['name' => 'Desa Panggul', 'email' => 'panggul.panggul@trenggalekkab.go.id'],
                ['name' => 'Desa Sawahan', 'email' => 'sawahan.panggul@trenggalekkab.go.id'],
                ['name' => 'Desa Tangkil', 'email' => 'tangkil.panggul@trenggalekkab.go.id'],
                ['name' => 'Desa Terbis', 'email' => 'terbis.panggul@trenggalekkab.go.id'],
                ['name' => 'Desa Wonocoyo', 'email' => 'wonocoyo.panggul@trenggalekkab.go.id'],
                ['name' => 'Desa Bendorejo', 'email' => 'bendorejo.pogalan@trenggalekkab.go.id'],
                ['name' => 'Desa Gembleb', 'email' => 'gembleb.pogalan@trenggalekkab.go.id'],
                ['name' => 'Desa Kedunglurah', 'email' => 'kedunglurah.pogalan@trenggalekkab.go.id'],
                ['name' => 'Desa Ngadirejo', 'email' => 'ngadirejo.pogalan@trenggalekkab.go.id'],
                ['name' => 'Desa Ngadirenggo', 'email' => 'ngadirenggo.pogalan@trenggalekkab.go.id'],
                ['name' => 'Desa Ngetal', 'email' => 'ngetal.pogalan@trenggalekkab.go.id'],
                ['name' => 'Desa Ngulankulon', 'email' => 'ngulankulon.pogalan@trenggalekkab.go.id'],
                ['name' => 'Desa Ngulanwetan', 'email' => 'ngulanwetan.pogalan@trenggalekkab.go.id'],
                ['name' => 'Desa Pogalan', 'email' => 'pogalan.pogalan@trenggalekkab.go.id'],
                ['name' => 'Desa Wonocoyo', 'email' => 'wonocoyo.pogalan@trenggalekkab.go.id'],
                ['name' => 'Desa Joho', 'email' => 'joho.pule@trenggalekkab.go.id'],
                ['name' => 'Desa Jombok', 'email' => 'jombok.pule@trenggalekkab.go.id'],
                ['name' => 'Desa Karanganyar', 'email' => 'karanganyar.pule@trenggalekkab.go.id'],
                ['name' => 'Desa Kembangan', 'email' => 'kembangan.pule@trenggalekkab.go.id'],
                ['name' => 'Desa Pakel', 'email' => 'pakel.pule@trenggalekkab.go.id'],
                ['name' => 'Desa Pule', 'email' => 'pule.pule@trenggalekkab.go.id'],
                ['name' => 'Desa Puyung', 'email' => 'puyung.pule@trenggalekkab.go.id'],
                ['name' => 'Desa Sidomulyo', 'email' => 'sidomulyo.pule@trenggalekkab.go.id'],
                ['name' => 'Desa Sukokidul', 'email' => 'sukokidul.pule@trenggalekkab.go.id'],
                ['name' => 'Desa Tanggaran', 'email' => 'tanggaran.pule@trenggalekkab.go.id'],
                ['name' => 'Desa Gamping', 'email' => 'gamping.suruh@trenggalekkab.go.id'],
                ['name' => 'Desa Mlinjon', 'email' => 'mlinjon.suruh@trenggalekkab.go.id'],
                ['name' => 'Desa Nglebo', 'email' => 'nglebo.suruh@trenggalekkab.go.id'],
                ['name' => 'Desa Ngrandu', 'email' => 'ngrandu.suruh@trenggalekkab.go.id'],
                ['name' => 'Desa Puru', 'email' => 'puru.suruh@trenggalekkab.go.id'],
                ['name' => 'Desa Suruh', 'email' => 'suruh.suruh@trenggalekkab.go.id'],
                ['name' => 'Desa Wonokerto', 'email' => 'wonokerto.suruh@trenggalekkab.go.id'],
                ['name' => 'Kelurahan Ngantru', 'email' => 'ngantru.trenggalek@trenggalekkab.go.id'],
                ['name' => 'Kelurahan Tamanan', 'email' => 'tamanan.trenggalek@trenggalekkab.go.id'],
                ['name' => 'Kelurahan Kelutan', 'email' => 'kelutan.trenggalek@trenggalekkab.go.id'],
                ['name' => 'Kelurahan Sumbergedong', 'email' => 'sumbergedong.trenggalek@trenggalekkab.go.id'],
                ['name' => 'Kelurahan Surodakan', 'email' => 'surodakan.trenggalek@trenggalekkab.go.id'],
                ['name' => 'Desa Sambirejo', 'email' => 'sambirejo.trenggalek@trenggalekkab.go.id'],
                ['name' => 'Desa Parakan', 'email' => 'parakan.trenggalek@trenggalekkab.go.id'],
                ['name' => 'Desa Rejowinangun', 'email' => 'rejowinangun.trenggalek@trenggalekkab.go.id'],
                ['name' => 'Desa Dawuhan', 'email' => 'dawuhan.trenggalek@trenggalekkab.go.id'],
                ['name' => 'Desa Sukosari', 'email' => 'sukosari.trenggalek@trenggalekkab.go.id'],
                ['name' => 'Desa Karangsoko', 'email' => 'karangsoko.trenggalek@trenggalekkab.go.id'],
                ['name' => 'Desa Ngares', 'email' => 'ngares.trenggalek@trenggalekkab.go.id'],
                ['name' => 'Desa Sumberdadi', 'email' => 'sumberdadi.trenggalek@trenggalekkab.go.id'],
                ['name' => 'Desa Banaran', 'email' => 'banaran.tugu@trenggalekkab.go.id'],
                ['name' => 'Desa Dermosari', 'email' => 'dermosari.tugu@trenggalekkab.go.id'],
                ['name' => 'Desa Duren', 'email' => 'duren.tugu@trenggalekkab.go.id'],
                ['name' => 'Desa Gading', 'email' => 'gading.tugu@trenggalekkab.go.id'],
                ['name' => 'Desa Gondang', 'email' => 'gondang.tugu@trenggalekkab.go.id'],
                ['name' => 'Desa Jambu', 'email' => 'jambu.tugu@trenggalekkab.go.id'],
                ['name' => 'Desa Ngepeh', 'email' => 'ngepeh.tugu@trenggalekkab.go.id'],
                ['name' => 'Desa Nglinggis', 'email' => 'nglinggis.tugu@trenggalekkab.go.id'],
                ['name' => 'Desa Nglongsor', 'email' => 'nglongsor.tugu@trenggalekkab.go.id'],
                ['name' => 'Desa Prambon', 'email' => 'prambon.tugu@trenggalekkab.go.id'],
                ['name' => 'Desa Pucanganak', 'email' => 'pucanganak.tugu@trenggalekkab.go.id'],
                ['name' => 'Desa Sukorejo', 'email' => 'sukorejo.tugu@trenggalekkab.go.id'],
                ['name' => 'Desa Tegaren', 'email' => 'tegaren.tugu@trenggalekkab.go.id'],
                ['name' => 'Desa Tumpuk', 'email' => 'tumpuk.tugu@trenggalekkab.go.id'],
                ['name' => 'Desa Winong', 'email' => 'winong.tugu@trenggalekkab.go.id'],
                ['name' => 'Desa Dukuh', 'email' => 'dukuh.watulimo@trenggalekkab.go.id'],
                ['name' => 'Desa Gemaharjo', 'email' => 'gemaharjo.watulimo@trenggalekkab.go.id'],
                ['name' => 'Desa Karanggandu', 'email' => 'karanggandu.watulimo@trenggalekkab.go.id'],
                ['name' => 'Desa Margomulyo', 'email' => 'margomulyo.watulimo@trenggalekkab.go.id'],
                ['name' => 'Desa Ngembel', 'email' => 'ngembel.watulimo@trenggalekkab.go.id'],
                ['name' => 'Desa Pakel', 'email' => 'pakel.watulimo@trenggalekkab.go.id'],
                ['name' => 'Desa Prigi', 'email' => 'prigi.watulimo@trenggalekkab.go.id'],
                ['name' => 'Desa Sawahan', 'email' => 'sawahan.watulimo@trenggalekkab.go.id'],
                ['name' => 'Desa Slawe', 'email' => 'slawe.watulimo@trenggalekkab.go.id'],
                ['name' => 'Desa Tasikmadu', 'email' => 'tasikmadu.watulimo@trenggalekkab.go.id'],
                ['name' => 'Desa Watuagung', 'email' => 'watuagung.watulimo@trenggalekkab.go.id'],
                ['name' => 'Desa Watulimo', 'email' => 'watulimo.watulimo@trenggalekkab.go.id'],
            ];
            
            // Ambil semua entitas yang sudah ada untuk ditautkan
            $entitiesLookup = Entity::pluck('id', 'name');
            $klienRoleId = $roles['Klien Eksternal'] ?? null;

            if($klienRoleId) {
                foreach ($externalClientData as $clientData) {
                    $entityId = $entitiesLookup[$clientData['name']] ?? null;

                    if ($entityId) {
                        User::firstOrCreate(
                            ['entity_id' => $entityId],
                            [
                                'name' => 'Admin ' . $clientData['name'],
                                'email' => $clientData['email'],
                                'password' => $defaultPassword,
                                'role_id' => $klienRoleId,
                                'jabatan' => 'Admin ' . (Str::startsWith($clientData['name'], 'Desa') ? 'Desa' : 'OPD'),
                            ]
                        );
                    }
                }
            }
        }
    }
}